[project]
name = "nora"
version = "3.5"
description = "NoRA Tools for scientific reading with Notion or Obsidian"
authors = [{ name = "Damien Robert", email = "damien.robert@uzh.ch" }]
requires-python = ">=3.9"
dependencies = [
    "psutil",
    "omegaconf",
    "pyyaml",
    "click",
    "requests",
    "arxiv",
    "notion-client",
    "notional",
    "pyrootutils",
    "pyzotero",
    "mistletoe",
    "markdownify",
    "rapidfuzz",
]

[project.optional-dependencies]
dev = ["pytest>=7"]

[project.scripts]
nora = "nora.utils.cli:cli"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"nora" = [
    "configs/**/*.yaml",
    "translation_server/**",
    "translation_server/**/*"
]
